---
kind: pipeline
name: build
trigger:
  branch:
    - master
  event:
    exclude:
      - promote
      - rollback

steps:
  - name: build
    image: node:16.14.2-alpine3.15
    commands:
      - npm ci
      - npm run build

  - name: publish
    image: plugins/docker
    settings:
      registry: registry.home.devmem.ru
      repo: registry.home.devmem.ru/gia/front
      dockerfile: ./compose/Dockerfile
      tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - latest
