export const EMAIL_REGEX = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/

export const USER_LOGOUT = 'USER_LOGOUT'

export const MODAL_SHOW = 'MODAL_SHOW'
export const MODAL_HIDE = 'MODAL_HIDE'

export const TOKEN_CHECK_SUCCESS = 'TOKEN_CHECK_SUCCESS'
export const TOKEN_CHECK_FAILURE = 'TOKEN_CHECK_FAILURE'
export const TOKEN_SAVE = 'TOKEN_SAVE'
export const USER_LOGIN_CHECKBOX = 'USER_LOGIN_CHECKBOX'

// export const TOKEN_SAVE_SESSION = 'TOKEN_SAVE_SESSION'
// export const TOKEN_SAVE_LOCAL = 'TOKEN_SAVE_LOCAL'

export const USER_LOGIN_ERRORS_REMOVE = 'USER_LOGIN_ERRORS_REMOVE'
export const USER_PASSWORD_RESET_ERRORS_REMOVE = 'USER_PASSWORD_RESET_ERRORS_REMOVE'
export const USER_PASSWORD_RESET_CONFIRM_ERRORS_REMOVE = 'USER_PASSWORD_RESET_CONFIRM_ERRORS_REMOVE'
export const USER_REG_ERRORS_REMOVE = 'USER_REG_ERRORS_REMOVE'
export const USER_INFO_UPDATE_ERRORS_REMOVE = 'USER_INFO_UPDATE_ERRORS_REMOVE'
export const USER_PASSWORD_CHANGE_ERRORS_REMOVE = 'USER_PASSWORD_CHANGE_ERRORS_REMOVE'
export const USER_REG_VERIFY_MAIL_ERRORS_REMOVE = 'USER_REG_VERIFY_MAIL_ERRORS_REMOVE'

// https://django-rest-auth.readthedocs.io/en/latest/api_endpoints.html
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'

export const USER_PASSWORD_RESET_REQUEST = 'USER_PASSWORD_RESET_REQUEST'
export const USER_PASSWORD_RESET_SUCCESS = 'USER_PASSWORD_RESET_SUCCESS'
export const USER_PASSWORD_RESET_FAILURE = 'USER_PASSWORD_RESET_FAILURE'

export const USER_PASSWORD_RESET_CONFIRM_REQUEST = 'USER_PASSWORD_RESET_CONFIRM_REQUEST'
export const USER_PASSWORD_RESET_CONFIRM_SUCCESS = 'USER_PASSWORD_RESET_CONFIRM_SUCCESS'
export const USER_PASSWORD_RESET_CONFIRM_FAILURE = 'USER_PASSWORD_RESET_CONFIRM_FAILURE'

export const USER_PASSWORD_CHANGE_REQUEST = 'USER_PASSWORD_CHANGE_REQUEST'
export const USER_PASSWORD_CHANGE_SUCCESS = 'USER_PASSWORD_CHANGE_SUCCESS'
export const USER_PASSWORD_CHANGE_FAILURE = 'USER_PASSWORD_CHANGE_FAILURE'

export const USER_INFO_REQUEST = 'USER_INFO_REQUEST'
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS'
export const USER_INFO_FAILURE = 'USER_INFO_FAILURE'

export const USER_INFO_UPDATE_REQUEST = 'USER_INFO_UPDATE_REQUEST'
export const USER_INFO_UPDATE_SUCCESS = 'USER_INFO_UPDATE_SUCCESS'
export const USER_INFO_UPDATE_FAILURE = 'USER_INFO_UPDATE_FAILURE'

export const USER_REG_REQUEST = 'USER_REG_REQUEST'
export const USER_REG_SUCCESS = 'USER_REG_SUCCESS'
export const USER_REG_FAILURE = 'USER_REG_FAILURE'

export const USER_REG_VERIFY_MAIL_REQUEST = 'USER_REG_VERIFY_MAIL_REQUEST'
export const USER_REG_VERIFY_MAIL_SUCCESS = 'USER_REG_VERIFY_MAIL_SUCCESS'
export const USER_REG_VERIFY_MAIL_FAILURE = 'USER_REG_VERIFY_MAIL_FAILURE'